<!doctype html>
<html class="cpprefjp" lang="ja" itemscope="" itemtype="http://schema.org/WebPage">
    <head>
        
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NXNBNVBTJS"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-NXNBNVBTJS');
</script>


        <meta charset="UTF-8">

        <title>set_unexpected - cpprefjp C++日本語リファレンス</title>

        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="keywords" content="
  C++,標準ライブラリ,リファレンス,ドキュメント,STL,std,exception,std,function,cpp11deprecated
">
        <meta name="title" content="set_unexpected - cpprefjp C++日本語リファレンス" />
        <meta itemprop="name" content="set_unexpected - cpprefjp C++日本語リファレンス" />
        <meta property="og:title" content="set_unexpected - cpprefjp C++日本語リファレンス" />
        <meta property="og:url" content="https://cpprefjp.github.io/reference/exception/set_unexpected.html" />
        <meta property="og:site_name" content="cpprefjp - C++日本語リファレンス" />
        <meta property="og:type" content="article" />
        <meta property="og:description" content="例外指定のある関数内で、指定外の例外が発生した時に呼び出される例外ハンドラを設定する。" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content="set_unexpected - cpprefjp C++日本語リファレンス" />
        <meta name="twitter:url" content="https://cpprefjp.github.io/reference/exception/set_unexpected.html" />
        <meta name="twitter:description" content="例外指定のある関数内で、指定外の例外が発生した時に呼び出される例外ハンドラを設定する。" />

        
  <link rel="alternate" type="application/atom+xml" title="Atom" href="https://cpprefjp.github.io/rss.xml" />


<link rel="apple-touch-icon" sizes="180x180" href="../../static/favicons/apple-touch-icon.png?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<link rel="icon" type="image/png" sizes="32x32" href="../../static/favicons/favicon-32x32.png?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<link rel="icon" type="image/png" sizes="16x16" href="../../static/favicons/favicon-16x16.png?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<link rel="manifest" href="../../manifest.json?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<meta name="theme-color" content="#f5f8fc">

<link rel="stylesheet" href="../../static/pygments/default.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<!-- <link rel="stylesheet" href="../../static/css/root.css"> -->

        
  


<link href="../../static/kunai/css/kunai-stage-0.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa" rel="stylesheet">
<link href="../../static/kunai/css/kunai-stage-1.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa" rel="stylesheet">
<link href="../../static/kunai/css/kunai-stage-2.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa" rel="stylesheet">
<link href="../../static/kunai/css/kunai-stage-3.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa" rel="stylesheet">

<script type="text/javascript" src="../../static/kunai/js/kunai-vendor.js?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa"></script>
<script type="text/javascript" src="../../static/kunai/js/kunai.js?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa"></script>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var kn = new Kunai;
    kn.cpprefjp();
  });
</script>

    </head>
    <body>
<header data-kunai-mdinfo="{&#34;meta&#34;: {&#34;header&#34;: [&#34;exception&#34;], &#34;namespace&#34;: [&#34;std&#34;], &#34;id-type&#34;: [&#34;function&#34;], &#34;cpp&#34;: [&#34;cpp11deprecated&#34;, &#34;cpp17removed&#34;]}, &#34;sources&#34;: [{&#34;id&#34;: &#34;5f189d0e29e9faa327e20c2c340638e86e6b231e&#34;, &#34;source&#34;: &#34;#include &lt;stdexcept&gt;\n#include &lt;iostream&gt;\n\nvoid unexpected_handler()\n{\n  std::cout &lt;&lt; \&#34;unexpected exception!\&#34; &lt;&lt; std::endl;\n  throw;\n}\n\nvoid other_throw() throw(int, std::bad_exception)\n{\n  throw 1.0;\n}\n\nint main()\n{\n  std::set_unexpected(unexpected_handler);\n\n  try {\n    other_throw();\n  }\n  catch(std::bad_exception) {\n    std::cout &lt;&lt; \&#34;bad_exception.\&#34; &lt;&lt; std::endl;\n  }\n\n  return 0;\n}\n&#34;}], &#34;page_id&#34;: [&#34;reference&#34;, &#34;exception&#34;, &#34;set_unexpected&#34;]}">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="../../index.html">
          <div class="title-wrapper clearfix">
            <div class="title">cpprefjp - C++日本語リファレンス</div>
          </div>
        </a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <div class="google-search">
              
  
<script>
  (function() {
    var cx = '013316413321391058734:ji_u66hl7hq';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<div class="gcse-search"></div>


            </div>
          </li>
          <li>
  <a href="https://github.com/cpprefjp/site">GitHub Project</a>
</li>
        </ul>
      </div>
    </div>
  </nav>
</header>

        <main id="main" role="main">
            <div class="container-fluid">
<div class="row">
  <div class="col-sm-9 col-sm-push-3" itemscope itemtype="http://schema.org/Article">
    <div class="row">
      <div class="col-sm-12 google-search-result">
        <gcse:searchresults></gcse:searchresults>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 content-header">
        
  <ol class="breadcrumb">
    
      <li  itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            <a href="../../index.html" itemprop="url">
              
                <i class="fa fa-fw fa-home"></i>
              
            </a>
          
        </span>
      </li>
    
      <li  itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            <a href="../../reference.html" itemprop="url">
              
                <span itemprop="name">リファレンス</span>
              
            </a>
          
        </span>
      </li>
    
      <li  itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            <a href="../../reference/exception.html" itemprop="url">
              
                <span itemprop="name">exception</span>
              
            </a>
          
        </span>
      </li>
    
      <li class="active" itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            
              <span itemprop="name">set_unexpected</span>
            
          
        </span>
      </li>
    
  </ol>
  <div class="crsearch"></div>

      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 edit-button">
        
  
    <p class="text-right"><small>
      最終更新日時(UTC):
      <span itemprop="datePublished" content="2019-02-12T07:01:02">
        2019年02月12日 07時01分02秒
      </span>
      <br/>
      <span itemprop="author" itemscope itemtype="http://schema.org/Person">
        <span itemprop="name">Akira Takahashi</span>
      </span>
      が更新
    </small></p>
  

        <p class="text-right">
          <a class="history" target="_blank" href="https://github.com/cpprefjp/site/commits/master/reference/exception/set_unexpected.md">
            <span class="fa fa-fw fa-clock-o fa-flip-horizontal"></span>履歴
          </a>
          <a class="edit" target="_blank" href="https://github.com/cpprefjp/site/edit/master/reference/exception/set_unexpected.md">
            <span class="fa fa-fw fa-pencil"></span>編集
          </a>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 content-body">
        
  <div class="identifier-type">function</div><div class="header">&lt;exception&gt;</div><h1 itemprop="name"><span class="namespace" title="namespace std">std::</span><span class="token">set_unexpected</span><span class="cpp cpp11deprecated text-warning" title="C++11で非推奨">(C++11で非推奨)</span><span class="cpp cpp17removed text-danger" title="C++17で削除">(C++17で削除)</span></h1>
<div itemprop="articleBody"><p><div class="codehilite"><pre><span></span><code><span class="k">namespace</span> <span class="n">std</span> <span class="p">{</span>
  <span class="k">using</span> <span class="n">unexpected_handler</span> <span class="o">=</span> <span class="kt">void</span><span class="p">(</span><span class="o">*</span><span class="p">)();</span>
  <span class="n">unexpected_handler</span> <span class="nf">set_unexpected</span> <span class="p">(</span><span class="n">unexpected_handler</span> <span class="n">f</span><span class="p">)</span> <span class="k">throw</span><span class="p">();</span>
<span class="p">}</span>
</code></pre></div>
</p>
<p>この関数はC++11から非推奨となり、C++17で削除された。<code>throw</code>キーワードの代わりに使用する<a href="../../lang/cpp11/noexcept.html"><code>noexcept</code>キーワード</a>では、指定外の<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>が発生することによるエラーは起こらない。</p>
<h2>概要</h2>
<p><a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>指定のある関数内で、指定外の<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>が発生した時に呼び出される<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>ハンドラを設定する。</p>
<h2><a class="cpprefjp-defined-word" data-desc="関数呼び出し式の評価結果となるオブジェクト・値">戻り値</a></h2>
<p>元設定されていた<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>ハンドラを返す。</p>
<h2>備考</h2>
<p>関数に<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>指定が行われている場合に、指定外の<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>が発生した場合、この関数で指定したハンドラを呼び出すように設定することが出来る。</p>
<p>また、ここで設定したハンドラは、プログラムから直接呼び出すことも出来る。定義外<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>ハンドラでは、「処理を終了する」もしくは、「<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>の送出」を行う。</p>
<p>何も送出しない場合は、終了処理が呼び出されプログラムが終了する。送出する場合は、<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>発生地点からの送出と等価の扱いとなる。<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>発生地点の関数の<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>指定が影響するため、<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>ハンドラ内で指定外の<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>が発生した場合は、<code>terminate()</code>が呼び出されプログラムが終了する。</p>
<p><a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>ハンドラ内には、カレントの<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>として、<code>bad_exception</code>が渡されておりthrowを呼び出すことで、<code>bad_exception</code>、その他の<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>を指定することで別の<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>を送出することが出来る。<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>ハンドラを設定しない場合、デフォルトでは、終了処理が発生する。</p>
<h2>例</h2>
<p><div class="yata" id="5f189d0e29e9faa327e20c2c340638e86e6b231e"><div class="codehilite"><pre><span></span><code><span class="cp">#include</span> <span class="cpf"><a href="../stdexcept.html">&lt;stdexcept&gt;</a></span><span class="cp"></span>
<span class="cp">#include</span> <span class="cpf"><a href="../iostream.html">&lt;iostream&gt;</a></span><span class="cp"></span>

<span class="kt">void</span> <span class="nf">unexpected_handler</span><span class="p">()</span>
<span class="p">{</span>
  <span class="n"><a href="../iostream/cout.html">std::cout</a></span> <span class="o">&lt;&lt;</span> <span class="s">"unexpected exception!"</span> <span class="o">&lt;&lt;</span> <span class="n"><a href="../ostream/endl.html">std::endl</a></span><span class="p">;</span>
  <span class="k">throw</span><span class="p">;</span>
<span class="p">}</span>

<span class="kt">void</span> <span class="nf">other_throw</span><span class="p">()</span> <span class="k">throw</span><span class="p">(</span><span class="kt">int</span><span class="p">,</span> <span class="n"><a href="bad_exception.html">std::bad_exception</a></span><span class="p">)</span>
<span class="p">{</span>
  <span class="k">throw</span> <span class="mf">1.0</span><span class="p">;</span>
<span class="p">}</span>

<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span>
<span class="p">{</span>
  <span class="n"><span style="color:#ff0000">std::set_unexpected</span></span><span class="p">(</span><span class="n">unexpected_handler</span><span class="p">);</span>

  <span class="k">try</span> <span class="p">{</span>
    <span class="n">other_throw</span><span class="p">();</span>
  <span class="p">}</span>
  <span class="k">catch</span><span class="p">(</span><span class="n"><a href="bad_exception.html">std::bad_exception</a></span><span class="p">)</span> <span class="p">{</span>
    <span class="n"><a href="../iostream/cout.html">std::cout</a></span> <span class="o">&lt;&lt;</span> <span class="s">"bad_exception."</span> <span class="o">&lt;&lt;</span> <span class="n"><a href="../ostream/endl.html">std::endl</a></span><span class="p">;</span>
  <span class="p">}</span>

  <span class="k">return</span> <span class="mi">0</span><span class="p">;</span>
<span class="p">}</span>
</code></pre></div>
</div></p>
<h3>出力</h3>
<p><pre><code>unexpected exception!
bad_exception.
</code></pre></p>
<h2>参照</h2>
<ul>
<li><a href="../../lang/cpp17/remove_deprecated_exception_specifications.html">C++17 非推奨だった古い例外仕様を削除</a></li>
</ul></div>

      </div>
    </div>
  </div>
  
  
    <div id="sidebar" class="col-sm-3 col-sm-pull-9">
    </div>
  

</div>
            </div>
        </main>
<footer class="footer navbar navbar-default">
  <div class="container-fluid">
    <p><small>
      本サイトの情報は、
        <a href="https://creativecommons.org/licenses/by/3.0/deed.ja" rel="nofollow">クリエイティブ・コモンズ 表示 3.0 非移植 ライセンス(CC BY)</a>
      の下に提供されています。
    </small></p>
  </div>
</footer>
    </body>
</html>